import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="min-h-screen flex flex-col">
					<header className="flex justify-between items-center p-4 bg-gray-800 text-white">
						<Link href="/">
							<h1 className="text-xl cursor-pointer">TodoList</h1>
						</Link>
						<nav>
							{/* TODO: Hide unnecessary links */}
							<Link className="mr-4" href="/sign-in">
								Sign in
							</Link>
							<Link className="mr-4" href="/sign-up">
								Sign up
							</Link>
						</nav>
					</header>
					<main className="flex-grow p-4">{children}</main>
					<footer className="p-4 bg-gray-800 text-white text-center">
						made by V
					</footer>
				</div>
			</body>
		</html>
	);
}
